### ISSUE TITLE
Import sheet breaks for the Generic B Tree

### ISSUE THREAD

**Issue by rahmansunny071** [dataspread/dataspread-web#150]
Here is a dump of the exception I am getting. Note that, the import issue with Cloning is fixed and works fine the master branch. 
@xzhou23 @mangeshbendre 

01-Nov-2017 17:46:27.783 SEVERE [http-nio-8080-exec-2] org.zkoss.zss.app.ui.AppCtrl.doOpenNewBook0:621 sheet name 'Sheet1' is duplicated
 org.zkoss.zss.model.InvalidModelOpException: sheet name 'Sheet1' is duplicated
	at org.zkoss.zss.model.impl.BookImpl.checkLegalSheetName(BookImpl.java:451)
	at org.zkoss.zss.model.impl.BookImpl.createSheet(BookImpl.java:327)
	at org.zkoss.zss.model.impl.BookImpl.createSheet(BookImpl.java:302)
	at org.zkoss.zss.app.ui.AppCtrl.doOpenNewBook0(AppCtrl.java:616)
	at org.zkoss.zss.app.ui.AppCtrl.doOpenNewBook(AppCtrl.java:593)
	at org.zkoss.zss.app.ui.AppCtrl.onAppEvent(AppCtrl.java:980)
	at org.zkoss.zss.app.ui.CtrlBase$1.onEvent(CtrlBase.java:67)
	at org.zkoss.zk.ui.AbstractComponent.onEvent(AbstractComponent.java:2752)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2723)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2664)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:136)
	at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1765)
	at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1550)
	at org.zkoss.zk.ui.impl.UiEngineImpl.execNewPage0(UiEngineImpl.java:512)
	at org.zkoss.zk.ui.impl.UiEngineImpl.execNewPage(UiEngineImpl.java:356)
	at org.zkoss.zk.ui.http.DHtmlLayoutServlet.process(DHtmlLayoutServlet.java:217)
	at org.zkoss.zk.ui.http.DHtmlLayoutServlet.doGet(DHtmlLayoutServlet.java:136)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

01-Nov-2017 17:46:28.362 INFO [http-nio-8080-exec-3] org.model.AutoRollbackConnection.<init> Opening connection at org.zkoss.zss.app.impl.CollaborationInfoImpl.setRelationship(CollaborationInfoImpl.java:98)
01-Nov-2017 17:46:28.362 INFO [http-nio-8080-exec-3] org.model.AutoRollbackConnection.close Closing connection at org.zkoss.zss.app.impl.CollaborationInfoImpl.setRelationship(CollaborationInfoImpl.java:110)
01-Nov-2017 17:46:28.362 INFO [http-nio-8080-exec-3] org.model.AutoRollbackConnection.close Open connections: 2
01-Nov-2017 17:46:28.377 INFO [http-nio-8080-exec-3] org.model.AutoRollbackConnection.<init> Opening connection at org.zkoss.zss.app.impl.CollaborationInfoImpl.setRelationship(CollaborationInfoImpl.java:98)
01-Nov-2017 17:46:28.377 INFO [http-nio-8080-exec-3] org.model.AutoRollbackConnection.close Closing connection at org.zkoss.zss.app.impl.CollaborationInfoImpl.setRelationship(CollaborationInfoImpl.java:110)
01-Nov-2017 17:46:28.377 INFO [http-nio-8080-exec-3] org.model.AutoRollbackConnection.close Open connections: 2
01-Nov-2017 17:46:28.846 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\manager
01-Nov-2017 17:46:29.159 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
01-Nov-2017 17:46:29.159 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
01-Nov-2017 17:46:29.159 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/manager] startup failed due to previous errors
01-Nov-2017 17:46:29.174 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\manager has finished in 328 ms
01-Nov-2017 17:46:37.824 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.<init> Opening connection at org.zkoss.zss.model.impl.BookImpl.checkDBSchema(BookImpl.java:170)
01-Nov-2017 17:46:38.293 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Closing connection at org.zkoss.zss.model.impl.BookImpl.checkDBSchema(BookImpl.java:211)
01-Nov-2017 17:46:38.293 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Open connections: 2
01-Nov-2017 17:46:38.293 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.<init> Opening connection at org.zkoss.zss.model.impl.BookImpl.createSheet(BookImpl.java:345)
01-Nov-2017 17:46:38.434 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Closing connection at org.zkoss.zss.model.impl.BookImpl.createSheet(BookImpl.java:361)
01-Nov-2017 17:46:38.434 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Open connections: 2
01-Nov-2017 17:46:38.434 INFO [http-nio-8080-exec-6] org.zkoss.zss.model.impl.Hybrid_Model.importSheet Importing sheet
01-Nov-2017 17:46:38.434 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.<init> Opening connection at org.zkoss.zss.model.impl.Hybrid_Model.importSheet(Hybrid_Model.java:746)
01-Nov-2017 17:46:38.512 INFO [http-nio-8080-exec-6] org.zkoss.zss.model.impl.ROM_Model.importSheet Importing sheet
01-Nov-2017 17:46:38.543 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.<init> Opening connection at org.zkoss.zss.model.impl.ROM_Model.importSheet(ROM_Model.java:378)
org.postgresql.util.PSQLException: ERROR: column "col_null" of relation "vj9hmszz12_2" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:313)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:294)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:294)
	at org.zkoss.zss.model.impl.ROM_Model.insertCols(ROM_Model.java:86)
	at org.zkoss.zss.model.impl.ROM_Model.importSheet(ROM_Model.java:392)
	at org.zkoss.zss.model.impl.Hybrid_Model.importSheet(Hybrid_Model.java:755)
	at org.zkoss.zss.app.ui.AppCtrl$15.onEvent(AppCtrl.java:542)
	at org.zkoss.zss.app.ui.AppCtrl$15.onEvent(AppCtrl.java:519)
	at org.zkoss.zul.impl.FileuploadDlg.onClose(FileuploadDlg.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2736)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2664)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:136)
	at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1765)
	at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1550)
	at org.zkoss.zk.ui.impl.UiEngineImpl.execUpdate(UiEngineImpl.java:1260)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.process(DHtmlUpdateServlet.java:603)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:485)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doPost(DHtmlUpdateServlet.java:494)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
01-Nov-2017 17:46:38.574 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Closing connection at org.zkoss.zss.model.impl.ROM_Model.importSheet(ROM_Model.java:423)
01-Nov-2017 17:46:38.574 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Open connections: 3
org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:971)
	at org.postgresql.core.v3.QueryExecutorImpl.startCopy(QueryExecutorImpl.java:688)
	at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:53)
	at org.zkoss.zss.model.impl.ROM_Model.importSheet(ROM_Model.java:400)
	at org.zkoss.zss.model.impl.Hybrid_Model.importSheet(Hybrid_Model.java:755)
	at org.zkoss.zss.app.ui.AppCtrl$15.onEvent(AppCtrl.java:542)
	at org.zkoss.zss.app.ui.AppCtrl$15.onEvent(AppCtrl.java:519)
	at org.zkoss.zul.impl.FileuploadDlg.onClose(FileuploadDlg.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2736)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2664)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:136)
	at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1765)
	at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1550)
	at org.zkoss.zk.ui.impl.UiEngineImpl.execUpdate(UiEngineImpl.java:1260)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.process(DHtmlUpdateServlet.java:603)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:485)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doPost(DHtmlUpdateServlet.java:494)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
01-Nov-2017 17:46:38.606 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Closing connection at org.zkoss.zss.model.impl.Hybrid_Model.importSheet(Hybrid_Model.java:768)
01-Nov-2017 17:46:38.606 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Open connections: 2
01-Nov-2017 17:46:38.621 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.<init> Opening connection at org.zkoss.zss.model.impl.SheetImpl.getEndColumnIndex(SheetImpl.java:493)
01-Nov-2017 17:46:38.621 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Closing connection at org.zkoss.zss.model.impl.SheetImpl.getEndColumnIndex(SheetImpl.java:498)
01-Nov-2017 17:46:38.621 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Open connections: 2
01-Nov-2017 17:46:38.637 SEVERE [http-nio-8080-exec-6] org.zkoss.zk.ui.impl.UiEngineImpl.handleError 
 org.zkoss.zk.ui.UiException: java.lang.NullPointerException
	at org.zkoss.zul.impl.FileuploadDlg.onClose(FileuploadDlg.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2736)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2664)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:136)
	at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1765)
	at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1550)
	at org.zkoss.zk.ui.impl.UiEngineImpl.execUpdate(UiEngineImpl.java:1260)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.process(DHtmlUpdateServlet.java:603)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:485)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doPost(DHtmlUpdateServlet.java:494)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.zkoss.zss.model.impl.Hybrid_Model.getBounds(Hybrid_Model.java:736)
	at org.zkoss.zss.model.impl.SheetImpl.getEndColumnIndex(SheetImpl.java:495)
	at org.zkoss.zss.ui.Spreadsheet.findDataBoundary(Spreadsheet.java:4178)
	at org.zkoss.zss.ui.Spreadsheet.initSheetMaxRowsCols(Spreadsheet.java:4326)
	at org.zkoss.zss.ui.Spreadsheet.getSheetMaxVisibleRows(Spreadsheet.java:4300)
	at org.zkoss.zss.ui.Spreadsheet.getCurrentMaxVisibleRows(Spreadsheet.java:3778)
	at org.zkoss.zss.ui.Spreadsheet.afterSheetSelected(Spreadsheet.java:2929)
	at org.zkoss.zss.ui.Spreadsheet.setSelectedSheet(Spreadsheet.java:3682)
	at org.zkoss.zss.app.ui.AppCtrl$15.onEvent(AppCtrl.java:552)
	at org.zkoss.zss.app.ui.AppCtrl$15.onEvent(AppCtrl.java:519)
	at org.zkoss.zul.impl.FileuploadDlg.onClose(FileuploadDlg.java:61)
	... 37 more

01-Nov-2017 17:46:38.653 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.<init> Opening connection at org.zkoss.zss.model.impl.SheetImpl.getEndColumnIndex(SheetImpl.java:493)
01-Nov-2017 17:46:38.653 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Closing connection at org.zkoss.zss.model.impl.SheetImpl.getEndColumnIndex(SheetImpl.java:498)
01-Nov-2017 17:46:38.653 INFO [http-nio-8080-exec-6] org.model.AutoRollbackConnection.close Open connections: 2
01-Nov-2017 17:46:38.653 SEVERE [http-nio-8080-exec-6] org.zkoss.zk.ui.impl.UiEngineImpl.handleError 
 java.lang.NullPointerException
	at org.zkoss.zss.model.impl.Hybrid_Model.getBounds(Hybrid_Model.java:736)
	at org.zkoss.zss.model.impl.SheetImpl.getEndColumnIndex(SheetImpl.java:495)
	at org.zkoss.zss.ui.Spreadsheet.findDataBoundary(Spreadsheet.java:4178)
	at org.zkoss.zss.ui.Spreadsheet.initSheetMaxRowsCols(Spreadsheet.java:4326)
	at org.zkoss.zss.ui.Spreadsheet.getSheetMaxVisibleColumns(Spreadsheet.java:4319)
	at org.zkoss.zss.ui.Spreadsheet.getCurrentMaxVisibleColumns(Spreadsheet.java:3765)
	at org.zkoss.zss.ui.Spreadsheet.createUnlockInfo(Spreadsheet.java:3904)
	at org.zkoss.zss.ui.Spreadsheet.updateUnlockInfo0(Spreadsheet.java:3887)
	at org.zkoss.zss.ui.Spreadsheet.access$1300(Spreadsheet.java:147)
	at org.zkoss.zss.ui.Spreadsheet$9.process(Spreadsheet.java:3875)
	at org.zkoss.zss.ui.Spreadsheet.processDeferOperations(Spreadsheet.java:4050)
	at org.zkoss.zss.ui.Spreadsheet.access$500(Spreadsheet.java:147)
	at org.zkoss.zss.ui.Spreadsheet$3.onEvent(Spreadsheet.java:388)
	at org.zkoss.zk.ui.AbstractComponent.onEvent(AbstractComponent.java:2752)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2723)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2664)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:136)
	at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1765)
	at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1550)
	at org.zkoss.zk.ui.impl.UiEngineImpl.execUpdate(UiEngineImpl.java:1260)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.process(DHtmlUpdateServlet.java:603)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:485)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doPost(DHtmlUpdateServlet.java:494)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

**Comment by Legandary23** [comment]
Fixed
